version: '3.4'

services:
  churchwebhelper:
    image: ghcr.io/bensteuem/churchwebhelper-debug:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - CT_DOMAIN=$CT_DOMAIN
      - COMMUNI_SERVER=$COMMUNI_SERVER
      - DEBUG=true
      - FLASK_ENV=development
      - FLASK_DEBUG=true