name: Docker Image CI pushing to GHCR for testing

on:
  push:
    branches: [ "dev_benste" ]
  pull_request:
    branches: [ "dev_benste"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Version from Python
        run:  echo "VERSION=$(python3 ./version.py)" >> $GITHUB_ENV

      - name: SHA_short
        run:  echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Show detected version number
        run: echo $VERSION

      -  name: Login to GitHub Container Registry
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Compose
        run: docker-compose build

      - name: Push to GHCR
        run: docker-compose push
